### ISSUE TITLE
Default ~/.emacs.d/ 

### ISSUE THREAD

**Issue by srustamo** [abo-abo/oremacs#8]
Does ~/.emacs.d dir gets used in your config? 

I'm not sure if ~/.emacs.d gets sourced during init (or created if it does not exist).

Many dotfiles get created in this dir by default, do these get created in ~/.emacs.d/ or in the 'emac-d' var defined dir?

**Comment by abo-abo** [comment]
> Does ~/.emacs.d dir gets used in your config?

No, it's not necessary for any Elisp files. But some package do store their files there: `bbdb`, `bookmarks`, `projectile.cache`, `recentf`, `smex-items`, `.mc-lists.el` etc.

The idea is to clone the config in some directory, and connect it only via `~/.emacs`

```elisp
;; (package-initialize)
(load "~/Dropbox/source/site-lisp/init.el")
```

This means that this will work as well, since the directory location no longer matters:

    emacs -Q -l init.el
